---
kerberos_client_packages_to_install:
  - krb5-workstation

kerberos_client_defaults_distribution:
  default_ccache_name: 'KEYRING:persistent:%{uid}'

# Enable facts deploiement
kerberos_client_facts: true

### KERBEROS SERVICE CONFIGURATION
# ---------------------------------------

# main client configuration
kerberos_client_config_file: /etc/krb5.conf

# host keytab
kerberos_client_keytab_path: /etc/krb5.keytab

# Default include directory
kerberos_client_include_dir: /etc/krb5.conf.d
# Additionnals include directory
kerberos_client_include_dirs: []

# The pattern or file name prefix to use to generate temporary
# keytab during sanitization
kerberos_client_keytab_sanitize_tmp_file_pattern: /tmp/keytab.sanitized

# Choose the way the role will fetch the keytab
# Available : none remote
#   none : the keytab will not be managed
#   remote : ansible will contact a remote kdc to produce the keytab (see variables below)
kerberos_client_keytab_deploy_method: none

## Theses variable are only relevant if the deploy method is set to remote

# Define the command that will produce the keytab on the remote KDC
# kerberos_client_keytab_deploy_remote_genkey_command:

# If yes, the remote command on KDC will not be logged
kerberos_client_keytab_deploy_remote_genkey_nolog: false

# Internal variable use to store the temporary file during transfert from KDC to initial host
kerberos_client_keytab_deploy_tmp_file: '/tmp/{{ inventory_hostname }}.keytab'

# The hostname to which delegate the keytab creation
# kerberos_client_keytab_deploy_remote_host:


### KERBEROS CONFIGURATION
# ---------------------------------------

# Host principal used to produce and check host keytab
kerberos_client_keytab_principal: 'host/{{ ansible_fqdn }}@EXAMPLE.COM'


kerberos_client_realms: {}
kerberos_client_defaults: {}
# List of domain mapping
kerberos_client_domains: {}
# List of logging rules
kerberos_client_logging: {}
# dbmodule per realm
kerberos_client_dbmodules: {}
# kerberos plugins
kerberos_client_plugins: {}

# Merged dict of defaults configurations items
kerberos_client_defaults_merged: '{{
    kerberos_client_defaults_distribution
    |combine(kerberos_client_defaults)
  }}'

# Default port of Kerberos service on KDC
kerberos_client_krb_port: 88
# Default port of Kerberos admin service on KDC
kerberos_client_krb_admin_port: 749
# Default port of kpasswd service
kerberos_client_krb_kpasswd_port: 464