---
kerberos_server_packages_to_install:
  - krb5-server
  - krb5-libs
  # Optional packages if you need to install those add-ons
  # - krb5-kdc-ldap
  # - ldap-utils
  # - krb5-pkinit
  # - krb5-otp
  # - krb5-k5tls
  # - libsasl2-modules-gssapi-mit
  # - libauthen-sasl-perl
  # - libauthen-sasl-cyrus-perl

#	Default values for KDC behavior
kerberos_server_kdcdefaults:
    master_key_type: "aes256-cts-hmac-sha1-96"
    des_crc_session_supported: false
    restrict_anonymous_to_tgt: true
    supported_enctypes:
            - "aes256-cts-hmac-sha1-96"
            - "normal camellia256-cts-cmac"
            - "normal aes128-cts-hmac-sha1-96"
            - "normal camellia128-cts-cmac"
            - "normal"

kerberos_server_dbdefaults:
  - ldap_kerberos_container_dn: "cn=krbContainer,dc=example,dc=com"

kerberos_server_dbmodules:
  - name: "EXAMPLE.COM"
    ldap_kdc_dn: "cn=admin,dc=example,dc=com"
    ldap_kadmind_dn: "cn=admin,dc=example,dc=com"
    ldap_service_password_file: /etc/krb5kdc/service.keyfile
    ldap_servers:
            - "ldaps://ldap01.example.com"
            - "ldaps://ldap02.example.com"
    ldap_conns_per_server: 5

kerberos_server_realms:
  - name: "EXAMPLE.COM"
    master_key_type: "aes256-cts-hmac-sha1-96"
    restrict_anonymous_to_tgt: true