---
- name: kerberos █ Create custom fact directory
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: kerberos █ Remove old fact file
  file:
    path: "{{ facts__dir|d('/etc/ansible/facts.d') }}/kerberos.fact"
    state: absent

- name: kerberos █ Insert custom fact file
  template:
    src: client/kerberos.fact.py.j2
    dest: "{{ facts__dir|d('/etc/ansible/facts.d') }}/kerberos_client.fact"
    owner: root
    group: root
    mode: 0755