---
- name: include_vars █ Gather OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/server.yml
  #
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/client_{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/client_{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/client_{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/client_{{ ansible_facts.os_family }}.yml"
        - "vars/client.yml"
      skip: true
  tags:
    - package

- name: Importing initialization tasks
  import_tasks: client/client_init.yml
  tags: ['always']

- name: Importing install tasks
  import_tasks: client/client_install.yml
  tags: ['kerberos-client-install']

- name: Importing configuration tasks
  import_tasks: client/client_configure.yml
  tags: ['kerberos-client-configure']

- name: Optionally including facts tasks
  include_tasks: client/client_facts.yml
  when: kerberos_client_facts|bool
  tags: ['kerberos-client-facts']
