---
- name: kerberos █ Importing client tasks
  import_tasks: client.yml
  when:
    - kerberos_profile == 'client'
  
- name: kerberos █ Importing server tasks
  import_tasks: server.yml
  when:
    - kerberos_profile == 'server'