---
- name: include_vars █ Gather OS specific variables
  # This task gathers variables defined in OS specific files.
  #
  # Search vars in:
  #  - <distribution>_<major>.yml    # eg. CentOS_8.yml
  #  - <os_family>_<major>.yml       # eg. RedHat_8.yml
  #  - <distribution>.yml            # eg. CentOS.yml
  #  - <os_family>.yml               # eg. RedHat.yml
  #
  # If no OS specific file is found, the role will default to vars/server.yml
  #
  include_vars: "{{ item }}"
  with_first_found:
    - files:
        - "vars/server_{{ ansible_facts.distribution | replace(' ','_') }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/server_{{ ansible_facts.os_family }}_{{ ansible_facts.distribution_major_version }}.yml"
        - "vars/server_{{ ansible_facts.distribution | replace(' ','_') }}.yml"
        - "vars/server_{{ ansible_facts.os_family }}.yml"
        - "vars/server.yml"
      skip: true
  tags:
    - package

- name: kerberos █ Install kerberos packages
  package:
    name: "{{ item }}"
    state: present
  with_items: "{{ kerberos_server_packages_to_install }}"
  tags:
    - package

# tasks file for ansible-krb5-server
- name: kerberos █ update kdc.conf configuration file
  template:
    src: server/kdc.conf.j2
    dest: /var/kerberos/krb5kdc/kdc.conf
    owner: root
    group: root
    mode: 0600
  tags:
    - configuration

# tasks file for ansible-krb5-server
- name: kerberos █ update krb5.conf configuration file
  template:
    src: server/krb5.conf.j2
    dest: /etc/krb5.conf
    owner: root
    group: root
    mode: 0600
  tags:
    - configuration

- name: restart krb5-kdc
  service:
    name: krb5-kdc
    state: restarted